version: "3.5"
services:
  laravel-app:
    build:
      context: '.'
      args:
        uid: 1000
    container_name: desafio-twgroup
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    user: "1000:1000"

  mysql:
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - "/home/dev/opt/docker/datadir/desafiotwgroup:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: desafiotwgroup
      MYSQL_USERNAME: twgroup
      MYSQL_PASSWORD: example
      TZ: "America/Caracas"
    cap_add:
      - SYS_NICE # CAP_SYS_NICE

#   redis:
#     image: redis:alpine
#     environment:
#       TZ: "America/Caracas"
#     ports:
#       - "6379:6379"
#     volumes:
#       - "/home/celr/opt/docker/datadir/redis/redis.conf:/usr/local/etc/redis/redis.conf"

  adminer:
    image: adminer
    environment:
      TZ: "America/Caracas"
    ports:
      - 8080:8080
    networks:
      - default
